# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Download artifact smws codes
      uses: dsaltares/fetch-gh-release-asset@0.06
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        file: "data.json"
        repo: "elliottback/SMWS_Codes"
        target: "./data.json"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install stuff
      run: npm ci
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
    - name: build
      run: npm run ci
    - name: Run headful puppeteer tests
      uses: djp3/puppeteer-headful@master
      with:
        args: npm test
    - name: Archive  artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        if-no-files-found: error
        path: |
          dist/*.png

  automerge:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: major
          github-token: ${{ secrets.PAT }}