name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download artifact smws codes
        uses: dsaltares/fetch-gh-release-asset@0.06
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: "data.json"
          repo: "elliottback/SMWS_Codes"
          target: "./data.json"

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run build --if-present --verbose && npm test

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release